name: Update Service Worker Version

on:
  push:
    branches:
      - main
    paths-ignore:
      - public/sw.js

jobs:
  update-sw-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.SW_TEST_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get latest commit hash
        id: get_commit_hash
        run: echo "commit_hash=$(git log --format=%H -1)" >> $GITHUB_OUTPUT

      - name: Update Service Worker Version
        run: node update-sw-version.js ${{ steps.get_commit_hash.outputs.commit_hash }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update service worker version"
          git push
